server:
  port: 4004

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sourav9599/config-server
          clone-on-start: true