version: '3'
services:
  service-registry:
    image: souravcoder99/service-registry-dockerapp:latest
    ports:
      - 8761:8761
  cloud-config-server:
    image: souravcoder99/cloud-config-server-dockerapp:latest
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://service-registry:8761/eureka
    depends_on:
      - service-registry
  cloud-gateway:
    image: souravcoder99/cloud-gateway-dockerapp:latest
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://service-registry:8761/eureka
    depends_on:
      - service-registry
      - cloud-config-server
    ports:
      - 4002:4002
  department-service:
    image: souravcoder99/department-service-dockerapp:latest
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://service-registry:8761/eureka
    restart: on-failure
    depends_on:
      - service-registry
      - cloud-config-server
  user-service:
    image: souravcoder99/user-service-dockerapp:latest
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://service-registry:8761/eureka
    restart: on-failure
    depends_on:
      - service-registry
      - cloud-config-server
      - department-service
  hystrix-dashboard:
    image: souravcoder99/hystrix-dashboard-dockerapp:latest
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://service-registry:8761/eureka
    depends_on:
      - service-registry
      - cloud-config-server  
    ports:
      - 4003:4003