server:
  port: 4001

spring:
  application:
    name: USER-SERVICE
   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://35.209.132.12:8761/eureka}
